controller:
  hostNetwork: true
  kind: DaemonSet
  daemonset:
    useHostPort: true
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  extraArgs:
    default-ssl-certificate: "default/nginx"
rbac:
  create: true
defaultBackend:
  enabled: true
